// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMrLWOtqFVFLkfnqi3e_y7TpPyKY64jrk',
    appId: '1:48960267437:web:49306facb93702017cd224',
    messagingSenderId: '48960267437',
    projectId: 'practicefirebase-ccb59',
    authDomain: 'practicefirebase-ccb59.firebaseapp.com',
    storageBucket: 'practicefirebase-ccb59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHy38UEDA_k3SoHTgwQKPRDGr54UeTAGU',
    appId: '1:48960267437:android:ad185e435aecb0c57cd224',
    messagingSenderId: '48960267437',
    projectId: 'practicefirebase-ccb59',
    storageBucket: 'practicefirebase-ccb59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGrxkEo8aJKl1HTweQjK5OpGU3kzyT7w',
    appId: '1:48960267437:ios:f486762dd0e97c887cd224',
    messagingSenderId: '48960267437',
    projectId: 'practicefirebase-ccb59',
    storageBucket: 'practicefirebase-ccb59.appspot.com',
    iosClientId: '48960267437-94f5jt3gjirbqiepg4mg8956mk17bj0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcGrxkEo8aJKl1HTweQjK5OpGU3kzyT7w',
    appId: '1:48960267437:ios:f486762dd0e97c887cd224',
    messagingSenderId: '48960267437',
    projectId: 'practicefirebase-ccb59',
    storageBucket: 'practicefirebase-ccb59.appspot.com',
    iosClientId: '48960267437-94f5jt3gjirbqiepg4mg8956mk17bj0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
